version: "2"
services:

  robotframework-python2-vvv:
    image: ckleinhuis/ufp-robotframework:15-python2
    environment:
      - LOG_LEVEL=vvv
      - "ROBOT_OPTIONS=--exclude python3"
    volumes:
      - ./robot:/opt/robotframework/tests
      - ./report/python2/v:/opt/robotframework/reports

  robotframework-python3-vvv:
    image: ckleinhuis/ufp-robotframework:15-python3
    environment:
      - "ROBOT_OPTIONS=--exclude python2"
      - LOG_LEVEL=vvv
    volumes:
      - ./robot:/opt/robotframework/tests
      - ./report/python3/v:/opt/robotframework/reports

  start-dependencies:
    image:  dadarek/wait-for-dependencies
    depends_on:
      - robotframework-python3-vvv
      - robotframework-python2-vvv
